### ISSUE TITLE
script used in config.yaml is missing

### ISSUE THREAD

**Issue by KasperJSdeVries** [m1chaelwilliams/make-windows-pretty#1]
In config.yaml you use a shell script to open zebar. This script is not included in the repository.

```yaml
general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ["shell-exec %userprofile%/.glzr/zebar/start.bat"]
``` 
https://github.com/m1chaelwilliams/make-windows-pretty/blob/7988ec653de7c85e5ae0309287eaf1bafc482960/config.yaml#L4C1-L4C71
